default:
  data_src:
    path: 'app/settings/resources/'
    filename: 'file.xlsx'

  databas:
    host: 0.0.0.0
    port: 5432
    db: 'postgres'
    user: 'postgres'
    passworld: 'postgres'

  merged_cells_order:
    fact_qoil_data_1: 'C3'
    fact_qoil_data_2: 'D3'
    forecast_qoil_data_1: 'G3'
    forecast_qoil_data_2: 'H3'
    fact_qliq_data_1: 'E3'
    fact_qliq_data_2: 'F3'
    forecast_qliq_data_1: 'I3'
    forecast_qliq_data_2: 'J3'

  date:
    m:  '6'
    y: '2022'